-- 1. Show all products.
SELECT * FROM sales

-- 2. Find products costing more than 300.
SELECT product_name, price
FROM sales
WHERE price > 300
ORDER BY price asc

-- 3. Find products with review score above 4.5.
SELECT product_name, review_score
FROM sales
WHERE review_score > 4.5
ORDER BY review_score desc

-- 4. Sort products by price in descending order.
SELECT product_name, price
FROM sales
ORDER BY price asc

-- 5. Find total revenue generated by all products.
SELECT SUM(total_sales) as "Total Revenue"
FROM sales

-- 6. Find average product price.
SELECT AVG(price) as "Average Product Price"
FROM sales

-- 7. Find the highest review score.
SELECT MAX(review_score)
FROM sales

-- 8. Count total number of products.
SELECT COUNT(product_name)
FROM sales

-- 9. Find total sales by product category.
SELECT category, SUM(total_sales)
FROM sales
GROUP BY category

-- 10. Find average review score by category.
SELECT category, AVG(review_score)
FROM sales
GROUP BY category

-- 11. Find the most reviewed category.
SELECT category, SUM(review_count) as "Total Reviews"
FROM sales
GROUP BY category
ORDER BY "Total Reviews" DESC
LIMIT 1

-- 12. Find total sales in Month 1.
SELECT SUM(sales_month_1) as "Total Sales in Month 1"
FROM sales

-- 13. Find the best sales month overall.
SELECT *
FROM
(
SELECT 'sales_month_1' as month, SUM(sales_month_1) as monthly_sales FROM sales
UNION ALL
SELECT 'sales_month_2', SUM(sales_month_2) FROM sales
UNION ALL
SELECT 'sales_month_3', SUM(sales_month_3) FROM sales
UNION ALL
SELECT 'sales_month_4', SUM(sales_month_4) FROM sales
UNION ALL
SELECT 'sales_month_5', SUM(sales_month_5) FROM sales
UNION ALL
SELECT 'sales_month_6', SUM(sales_month_6) FROM sales
UNION ALL
SELECT 'sales_month_7', SUM(sales_month_7) FROM sales
UNION ALL
SELECT 'sales_month_8', SUM(sales_month_8) FROM sales
UNION ALL
SELECT 'sales_month_9', SUM(sales_month_9) FROM sales
UNION ALL
SELECT 'sales_month_10', SUM(sales_month_10) FROM sales
UNION ALL
SELECT 'sales_month_11', SUM(sales_month_11) FROM sales
UNION ALL
SELECT 'sales_month_12', SUM(sales_month_12) FROM sales
)as monthly_sales
ORDER BY monthly_sales DESC
LIMIT 1

-- 14. Find products with increasing sales trend from Month 1 to Month 12.
SELECT product_name, category, sales_month_1, sales_month_12
FROM sales
WHERE sales_month_1 < sales_month_12
UNION ALL
SELECT 'Total Products', NULL, NULL, COUNT(*)
FROM sales
WHERE sales_month_1 < sales_month_12

-- 20. Find products with high reviews but low sales.
SELECT product_name, category, review_score, total_sales
FROM sales
WHERE review_score > (
SELECT AVG(review_score)
FROM sales
) AND total_sales < (
SELECT AVG(total_sales)
FROM sales
)
ORDER BY review_score DESC, total_sales ASC

-- 21. Find products with low reviews but high sales.
SELECT product_name, category, review_score, total_sales
FROM sales
WHERE review_score < (
SELECT AVG(review_score)
FROM sales
) AND total_sales > (
SELECT AVG(total_sales)
FROM sales
)
ORDER BY total_sales DESC, review_score ASC


-- 22. Rank products by total sales.
SELECT product_name, category, total_sales, RANK() OVER (ORDER BY total_sales DESC)
FROM sales

-- 23. Dense rank categories by revenue.
SELECT product_name, category, total_sales, DENSE_RANK() OVER (ORDER BY total_sales DESC)
FROM sales

-- 24. Find cumulative sales of products.
SELECT product_name, category, total_sales, SUM(total_sales) OVER (ORDER BY total_sales ASC) as "Cumulative Sales"
FROM sales

-- 25. Find which category performs best consistently across all months.
SELECT category, AVG(total_sales) as "Average Yearly Sales"
FROM sales
GROUP BY category
ORDER BY STDDEV(total_sales) DESC, "Average Yearly Sales" ASC
LIMIT 1

-- 26. Find seasonal products based on monthly sales trends.
SELECT product_name, category, (GREATEST(sales_month_1, sales_month_2, sales_month_3, sales_month_4, sales_month_5, sales_month_6, sales_month_7, sales_month_8, sales_month_9, sales_month_10, sales_month_11, sales_month_12) - LEAST(sales_month_1, sales_month_2, sales_month_3, sales_month_4, sales_month_5, sales_month_6, sales_month_7, sales_month_8, sales_month_9, sales_month_10, sales_month_11, sales_month_12)) as "Sales Variations"
FROM sales
ORDER BY "Sales Variations" DESC
LIMIT 20

-- 27. Find products with unstable sales patterns.
SELECT product_name, category, STDDEV(monthly_sales) AS "Sales Variations"
FROM
(
SELECT product_name, category, UNNEST(ARRAY[sales_month_1, sales_month_2, sales_month_3, sales_month_4, sales_month_5, sales_month_6, sales_month_7, sales_month_8, sales_month_9, sales_month_10, sales_month_11, sales_month_12]) as monthly_sales
FROM sales
)as monthly_data
GROUP BY product_name, category
ORDER BY "Sales Variations" DESC

-- 28. Find categories that depend heavily on reviews for sales.
SELECT category, AVG(review_score) AS avg_review_score, AVG(review_count) AS avg_review_count, AVG(total_sales) AS avg_sales
FROM sales
GROUP BY category
ORDER BY avg_review_score DESC, avg_review_count DESC, avg_sales DESC

-- 29. Find the product with the best revenue-to-review ratio.
SELECT product_name, category, (total_revenue / review_count) as "Revenue-to-Review Ratio"
FROM sales
ORDER BY "Revenue-to-Review Ratio" DESC
LIMIT 1

-- 30. Find the month with the highest company-wide revenue.
SELECT *
FROM
(
SELECT 'sales_month_1' as month, SUM(sales_month_1) as monthly_sales FROM sales
UNION ALL
SELECT 'sales_month_2', SUM(sales_month_2) FROM sales
UNION ALL
SELECT 'sales_month_3', SUM(sales_month_3) FROM sales
UNION ALL
SELECT 'sales_month_4', SUM(sales_month_4) FROM sales
UNION ALL
SELECT 'sales_month_5', SUM(sales_month_5) FROM sales
UNION ALL
SELECT 'sales_month_6', SUM(sales_month_6) FROM sales
UNION ALL
SELECT 'sales_month_7', SUM(sales_month_7) FROM sales
UNION ALL
SELECT 'sales_month_8', SUM(sales_month_8) FROM sales
UNION ALL
SELECT 'sales_month_9', SUM(sales_month_9) FROM sales
UNION ALL
SELECT 'sales_month_10', SUM(sales_month_10) FROM sales
UNION ALL
SELECT 'sales_month_11', SUM(sales_month_11) FROM sales
UNION ALL
SELECT 'sales_month_12', SUM(sales_month_12) FROM sales
)as monthly_sales
ORDER BY monthly_sales DESC
LIMIT 1